### ISSUE TITLE
array has incomplete element type 'struct rcd_rebinding'

### ISSUE THREAD

**Issue by crespoxiao** [facebook/FBRetainCycleDetector#11]
hey there,when i import this library,appears the compile problem "array has incomplete element type 'struct rcd_rebinding'",i set the file name AppDelegate.mm and import libc++.tbd still can not fix this problem.any good suggestion ? thanks.

![1](https://cloud.githubusercontent.com/assets/1168793/15773461/8ccc4eb6-29a9-11e6-9357-898b9d97068e.jpg)

**Comment by crespoxiao** [comment]
to the guys who searched this issue,
     it's not a common problem.the reason of this error is my workspace has 2 fishhook class files, one belongs to FBRetainCycleDetector lib and another belongs to a private lib. just keep one and it would be ok.

**Comment by kastiglione** [comment]
Thanks for the report, and the follow up.

I think `FBRetainCycleDetector` should either:

1. Add `rcd_` prefix to `fishhook.h`
2. Remove `rcd_` prefixes from functions in `fishhook.h`

Option 2 should be possible following facebook/fishhook#29

**Comment by k0nserv** [comment]
I'm also seeing this with React Native 0.49.0 which introduced a fishhook in https://github.com/facebook/react-native/commit/878b7e42fae990df745af2db6ac50cbac8a8ce1c. This causes a conflict because the project also depends on FBMemoryProfiler which in turn has a dependncy on `FBRetainCycleDetector` where another fishhhook exists. 

Is the only solution for this issue to remove one of the two?

**Comment by kastiglione** [comment]
@k0nservdo you mind pasting the compilation error?

It should be achievable to have both use fishhook independently without conflict.

**Comment by k0nserv** [comment]
It's the same as above regarding `rcd_rebinding`. I got lucky and we had stopped using `FBMemoryProfiler` so I could just remove it leaving us only with the `FBRetainCycleDetector` from React Native
